SilverStripe\ORM\DataObject:
  extensions:
    - Madmatt\EncryptAtRest\Extension\EncryptDataObjectFieldsExtension
Madmatt\EncryptAtRest\Extension\EncryptDataObjectFieldsExtension:
  EncryptedDataObjects:
    - EncryptDataObject
File:
  allowed_extensions:
    ["enc"]

SilverStripe\Core\Injector\Injector:
  EncryptedVarchar:
    class: Madmatt\EncryptAtRest\FieldType\EncryptedVarchar
